### ISSUE TITLE
按照说明部署BLumiaOJ未起作用

### ISSUE THREAD

**Issue by zryoung** [BLumia/BLumiaOJ#2]
你好，我现在装的是最新的hustoj.按照说明部署BLOJ不能用。提示无法连接数据库。请帮忙。能否留个联系方式，向你请教

**Comment by BLumia** [comment]
请检查你的OJ部署目录路径下的 `include/config.sample.php` 文件，你需要复制该文件并命名新的文件为 `config.php` (就是去掉 `sample` 字样)
``` shell
cd include/ # 切换到配置文件所在目录
cp config.sample.php config.php
```
接下来你需要编辑该文件(`config.php`)最下方的数据库信息([当前版本](https://github.com/BLumia/BLumiaOJ/blob/4d9762a51942bd738890c742e83c20d1643a26f4/include/config.sample.php#L56)的56~62行位置)，正确后即可成功连接数据库。注意你需要修改的是 `config.php` ，不是 `config.sample.php` 。

任何疑问可以继续回复该 issue ~

**Comment by zryoung** [comment]
是的，我改了。现在是这个错误：无法显示此网页

错误代码： HTTP ERROR 500
IP*** 目前无法处理此请求。

**Comment by zryoung** [comment]
@BLumia 我改$SQL_DB_NAME="jol",其它没改

**Comment by BLumia** [comment]
500 听上去不是 OJ 代码导致的，检查你所用的 httpd 的日志以便获取详细的错误信息，如果需要帮助，尝试提供更多信息以帮助判断错误原因。

根据你所使用的发行版和 httpd 不同，日志位置可能也不同，搜索即可查到日志位置。此前你也可以尝试重启你的 httpd (nginx / apache) 服务。

数据库配置你可以直接对比你之前的 HUSTOJ 配置文件中的配置以确保无误，包括数据库名称，用户名密码，以及端口号。

**Comment by wurong98** [comment]
.gitattributes	 
.gitignore	 
.htaccess
删除这些文件，http 500内部服务器（HTTP-Internal Server Error）
可以试试。

**Comment by zryoung** [comment]
我把setting_db.inc.php异常信息抛出来了：Database connect failed. Check the configure file and try again!SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution是什么问题？

**Comment by BLumia** [comment]
可能是你填写的数据库地址名称无法被解析，有可能是错误的DNS或者错误的填写造成的，如果你使用了 主机名称（包括写 `localhost`），可以尝试修改为 IP 地址（比如 `127.0.0.1`）并再次尝试是否依然出现这个错误。

Ref: [StackOverflow](https://stackoverflow.com/questions/6275535/php-error-php-network-getaddresses-getaddrinfo-failed-while-getting-informat)

**Comment by BLumia** [comment]
你的问题解决了吗？如果解决了，建议回复你实际出现的问题和解决方案以帮助遇到类似情况的人。如果没有解决，你依然可以继续回复并提供更多信息以帮助我们解决问题，如果你已解决问题，别忘记关闭（Close）该 Issue 。

**Comment by zryoung** [comment]
还没解决哦。能不能远程协助一下

**Comment by BLumia** [comment]
这个... 我个人建议你能够提供更多有助于判断错误原因的信息来解决问题而不是远程。
就目前你提供的信息而言，错误应该不是由 OJ 代码导致的，对于上面的解决方案，你是否已经尝试过将默认的 `localhost` 修改为 `127.0.0.1` 并重新尝试？如果已经尝试，并依然无法连接数据库，可否提供详细的异常信息？
当然如果你真的希望远程协助的话... 你可以通过给我发送邮件得到进一步的联系方式... 不过我依然不建议这样做...

**Comment by zryoung** [comment]
你好，怎么获得详细的异常信息？因为我对linux和php都一窍不通

**Comment by BLumia** [comment]
> 我改$SQL_DB_NAME="jol",其它没改

我默认配置写的数据库地址是 `localhost` ，你在改成 `127.0.0.1` 之后依然会有 `Database connect failed. Check the configure file and try again!SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution` 这个提示吗？

**Comment by zryoung** [comment]
是的，依然有这个错误。

**Comment by BLumia** [comment]
请贴一下你的 `config.php` 的 56~62行，即 `$ENV_CASE` 到 端口信息 位置。然后重新贴一下相应的报错内容。
如果你写 `127.0.0.1` 的话就不再需要 DNS 了，故应该也不会报 name resolution 的错。
也建议你试一试 `nslookup` 指令检查你的 DNS 是否有问题，如 `nslookup baidu.com` ，`nslookup localhost` 。

**Comment by 13037639065** [comment]
加我QQ聊吧  1667629529

**Comment by BLumia** [comment]
已经超过一周没有回复，我打算关闭该 issue ，如果你依然没有解决问题，你可以重新打开 issue 或尝试通过邮件联系我（因为看上去问题的确和该 repo 没关系）。

我依然尝试提供几个在安装过程比较容易出现的问题以及解决方案，你可以对照一下有没有这些问题：

> 部署完毕，提示无法连接数据库

请检查数据库配置（地址，用户名，端口）是否有误。你需要复制 `config.sample.php` 为 `config.php`  并修改其中的对应配置项以供使用。

> 修改配置文件完毕后无页面显示，日志显示 500 错误

请检查你的新配置文件的权限，所有者应为 `www-data` （或者你需要的用户），权限应为 `771` 。如果配置文件权限正常但依然 500 ，尝试检查你的 Apache 配置，或者删掉该 repo 附带的 `.htaccess` 文件。

> 修改配置文件完毕后依然无法连接数据库

sample 中默认的端口是 3307（我的开发环境所用的），常规情况我建议使用 3306 。另外如果提示无法解析，尝试把 `localhost` 改成 `127.0.0.1` 并再试。

如果你依然没有解决问题，请重新打开该 issue 并提供更多信息，如果你解决了，也建议回复一下你遇到的实际问题以及你是如何解决该问题的，以便帮助更多的人。谢谢。
