### ISSUE TITLE
请问论坛系统如何使用啊- -

### ISSUE THREAD

**Issue by 18332656500** [BLumia/BLumiaOJ#4]
之前HUSTOJ的帖子无法显示，

发帖子显示
```
Post failed!
Title or content can't be empty
```

十分感谢！

**Comment by BLumia** [comment]
标题和内容均不能为空，检查一下是不是留空了。
之前的帖子也不显示的话顺带检查一下数据库，以及看看直接访问你的 `站点地址/api/ajax_discuss.php` 能不能得到正确的 json 返回。
目前提供的信息我判断不了问题在哪，上面的内容检查过之后可以把结果帖一下，也可以顺带看看你的 error.log 有没有异常~

**Comment by 18332656500** [comment]
标题和内容都有内容，依旧是上面的问题。  感觉是数据库粗了问题？
可是我没动过topic和reply这两个表啊 - -
返回的信息是
```
{"status":200,"message":"OK"}
```
十分感谢

**Comment by BLumia** [comment]
查一下 error.log 吧，如果你用 apache & debian 系发行版 ，log 应该位于 `/var/log/apache2/error.log` ，可以 `tail -f error.log` 然后再次访问一下那个页面看一下有没有错误。

相关代码可以参见 [这里](https://github.com/BLumia/BLumiaOJ/blob/master/api/ajax_discuss.php#L75) 。也可以试着手动拼接然后执行一下这个 sql 看看能不能得到正确的结果。

**Comment by BLumia** [comment]
如果你还没有来得及查看问题，我[刚刚的一个提交](https://github.com/BLumia/BLumiaOJ/commit/9c27bf1b172a80866ba7dbd7f5b0d775e0b6e97b)增加了你这个问题相关位置的错误检查和输出（输出到 error.log 的），你可以更新一下然后再试着重复上面的步骤来找找问题在哪。

**Comment by 18332656500** [comment]
实在是麻烦您了。
我在我的/var/log/nginx目录下找到了error.log，tail -f error.log之后显示如下：
```
2018/08/15 13:52:45 [error] 947#947: *95317 FastCGI sent in stderr: "PHP message: PHP Warning:  preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead in /home/judge/src/web/include/safe_func.inc.php on line 95
PHP message: PHP Warning:  preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead in /home/judge/src/web/include/safe_func.inc.php on line 102" while reading response header from upstream, client: 183.197.172.138, server: _, request: "POST /api/ajax_discuss.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "127.0.0.1", referrer: "http://127.0.0.1/discuss.php"
2018/08/15 13:52:49 [error] 947#947: *95317 FastCGI sent in stderr: "PHP message: PHP Warning:  preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead in /home/judge/src/web/include/safe_func.inc.php on line 95
PHP message: PHP Warning:  preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead in /home/judge/src/web/include/safe_func.inc.php on line 102" while reading response header from upstream, client: 183.197.172.138, server: _, request: "POST /api/ajax_discuss.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "127.0.0.1", referrer: "http://127.0.0.1/discuss.php"
2018/08/15 13:56:36 [error] 947#947: *95336 FastCGI sent in stderr: "PHP message: PHP Warning:  preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead in /home/judge/src/web/include/safe_func.inc.php on line 95
PHP message: PHP Warning:  preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead in /home/judge/src/web/include/safe_func.inc.php on line 102" while reading response header from upstream, client: 183.197.172.138, server: _, request: "POST /api/ajax_discuss.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "127.0.0.1", referrer: "http://127.0.0.1/discuss.php"

```

**Comment by BLumia** [comment]
哦哦，`preg_replace()` 的 `\e` 在 PHP 5.5.0 之后[被废弃了](https://secure.php.net/manual/en/function.preg-replace.php#refsect1-function.preg-replace-errors)，所以会产生警告。你可以试着删除你的 [include/safe_func.inc.php](https://github.com/BLumia/BLumiaOJ/blob/master/include/safe_func.inc.php#L102) 的第 95 和 102 行，可以解决这个问题。（`[colorTxt]` 和 `[emot]` 这俩实际应该都不支持，也没人用吧，你修改完之后也可以提个 pull request 过来）。

但我不太确定这个和你最上面提到的 “标题和内容不能为空” 的 bug 是否相关，你可以在做出上面的修改之后再试试（别忘了在改之前先同步一下获取昨天晚上的那个提交），如果依然出问题的话，再次试着先 `tail -f` 然后访问 discuss 页面。

多谢反馈啦

**Comment by 18332656500** [comment]
删除那两行代码之后问题解决了。真的十分感谢！扫码了一点小小心意

**Comment by BLumia** [comment]
没事～

如果你想的话可以把这个变更提交个 pull request 过来，我给你合并进去～
