### ISSUE TITLE
依旧是讨论版一个小问题

### ISSUE THREAD

**Issue by 18332656500** [BLumia/BLumiaOJ#5]
使用BBCode时
[code]

[/code]
之间的逗号会自动变为空格，<>号也有些问题(这个我倒是会解决，但是变成了空格我就解决不好了)
Thanks

**Comment by BLumia** [comment]
哦哦，是 [`RemoveXSS()`](https://github.com/BLumia/BLumiaOJ/blob/28ec42a927c8039d79049ff61c0b4b0ca56ce13e/include/safe_func.inc.php#L15) 的一个正则写错了，`/([\x00-\x08,\x0b-\x0c,\x0e-\x19])/` [会把逗号也匹配进去](https://regexper.com/#%2F%28%5B%5Cx00-%5Cx08%2C%5Cx0b-%5Cx0c%2C%5Cx0e-%5Cx19%5D%29%2F) 。

把 [safe_func.inc.php 的第 15 行](https://github.com/BLumia/BLumiaOJ/blob/28ec42a927c8039d79049ff61c0b4b0ca56ce13e/include/safe_func.inc.php#L15) 改成
``` php
$val = preg_replace('/([\x00-\x08\x0b-\x0c\x0e-\x19])/', '', $val);
```` 
就好。有意愿的话可以改完发个 pull request 过来，没有的话告诉我一下我顺手修复掉~

`<>` 的问题是指什么？可以说详细一点吗？

**Comment by 18332656500** [comment]
没问题了，Thanks @_@
<> 的问题。。。我也忘记了，好像昨天也是因为逗号的问题引起的吧，总之现在都没问题了。
其实我上次就想问了。。“发个 pull request”是什么意思啊？

**Comment by BLumia** [comment]
GitHub 提供的 [关于 Pull Request](https://help.github.com/articles/about-pull-requests/) 帮助文档，或者问问搜索引擎咯。

大致的话是这个意思：我看你 fork （派生）了这个 repo （源代码仓库），那你就有了自己的一个版本，你可以在你自己的版本上进行任意变更，这时候变更是不会影响到原版（或者叫上游）。比方说你现在在你自己的版本里修复了一个 BUG ，而你希望这个 BUG 修复也能够合并到上游的代码中，这时候你就可以通过 GitHub 提供的 Pull Request 发起合并请求了。

具体的做法搜索引擎或者帮助文档会告诉你（还是挺简单的），如果你依然有意愿提交 Pull Request 的话我等你的 Pull Request ，觉得麻烦或者不想的话我就顺手直接修复掉这个问题了。

**Comment by 18332656500** [comment]
不用啦，你自己改吧😂
