### ISSUE TITLE
问题里该如何从本地导入图片呢？

### ISSUE THREAD

**Issue by 18332656500** [BLumia/BLumiaOJ#7]
图片链接可以导入，本地无法导入，请教改如何设置 T T

**Comment by BLumia** [comment]
检查一下你的 `OJ_PATH/include/config.php` 中的图片存储路径是不是配置正确了，如果路径存在的话检查一下那个路径的权限。

上传的图片会被存储到 `$OJ_UPLOAD_DATA` ，你可以检查一下从编辑问题那个页面点击上传图片并上传后在那个路径下找找有没有你上传的图片。

**Comment by BLumia** [comment]
你的问题定位到 / 解决了吗？如果解决了的话可以贴一下你实际遇到的问题是什么以及解决方式，如果只是使用方式的疑问并且现在已经没有疑问的话我就把 issue 关掉了...

**Comment by 18332656500** [comment]
您好，我的var/www/html/OnlineJudge/里没有uploads（也好像是没有OnlineJudge，记不清了）。   
我建立了这样的目录，但是不起作用，可能是您说的没有访问权限的问题，但是不知道该如何添加这个路径的访问权限呢？  
感谢！

**Comment by BLumia** [comment]
你可以指定为任意你希望的路径，默认给出的值是仅供参考的。权限的话把你所指定的目录路径 [`chown`](https://linux.die.net/man/1/chown) 给你的 httpd 所使用的用户（大多时候默认是 `www-data` ），或保证 `www-data` 能够读写你的那个目录即可。
