### ISSUE TITLE
请问添加新的语言加在哪，php看不懂。。

### ISSUE THREAD

**Issue by LTitan** [BLumia/BLumiaOJ#8]

**Comment by BLumia** [comment]
对于你想要支持的新语言，在 [language](https://github.com/BLumia/BLumiaOJ/tree/master/language) 目录下，复制现有的 `english.admin.inc.php` 和 `english.inc.php` 并重命名为 `语言名称.admin.inc.php` 和 `语言名称.inc.php` ，并修改里面的翻译就行了。

一切准备就绪后，修改 [配置文件内的对应配置](https://github.com/BLumia/BLumiaOJ/blob/master/include/config.sample.php#L5) 即可生效。

语言名称实际上是可以随意的（和配置文件内的写法保持一致即可），不过在开发 BLumiaOJ 时，这个名称使用的是 [Valve 的规则](https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/common/language.cpp#L31)，可供参考。

**Comment by LTitan** [comment]
emm，作者误解了，哈哈哈，我的意思是新的程序语言

**Comment by BLumia** [comment]
> 我的意思是新的程序语言

对于新增 hustoj 判题核心现在已经支持的程序语言（编译器），修改 [$OJ_LANGMASK](https://github.com/BLumia/BLumiaOJ/blob/master/include/config.sample.php#L14) 的值即可。规则可参见 [$LANGUAGE_NAME](https://github.com/BLumia/BLumiaOJ/blob/master/include/common_const.inc.php#L7) 。自己根据需要计算 language mask 的值。

若要为 hustoj 判题核心新增其他语言的支持，就需要修改 hustoj 判题核心的代码了。虽然之前看过但是现在没有印象了，可能需要你自己研究。

**Comment by LTitan** [comment]
好嘞，谢谢老哥了

**Comment by BLumia** [comment]
好嘞，没问题我就关 issue 了～
