### ISSUE TITLE
发现了个问题就是导入问题的时候说权限不够，

### ISSUE THREAD

**Issue by LTitan** [BLumia/BLumiaOJ#9]

**Comment by BLumia** [comment]
你所配置的问题存储目录应当具有合适的权限。检查相应目录的权限以及所涉及用户是否能够正常进行数据写入。

你的描述过于简单以至于我没办法做出更具体的回答，如果希望更具体的回答，请提供更多有用的信息，比如你的 PHP 错误日志（error.log），具体目录的所有者以及权限等信息。

**Comment by LTitan** [comment]
![default](https://user-images.githubusercontent.com/32760810/49509954-d8887c00-f8c1-11e8-8c4e-47120bae53b4.png)

emm,这种情况您有遇到过么

**Comment by BLumia** [comment]
提示不是已经告诉你做法了么...

请尝试 `chgrp -R www-data /home/judge/data` 以及 `chmod -R 771 /home/judge/data`

**Comment by LTitan** [comment]
但是好像没用用的

**Comment by BLumia** [comment]
`ls -lah /home/judge` 贴输出，`ls -lah /home/judge/data | grep 1001` 贴输出

**Comment by BLumia** [comment]
一周没回复了，我先关掉问题了。

如果你依然没有解决问题，建议检查你配置文件内指定的对应目录的权限是不是正确，至少需要保证你的 httpd 对应的用户（一般是 `www-data`）具备写入权限。你也可以参考 hustoj 安装脚本中的做法对照。
